:memo: docs(env): update readme

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,9 +4,14 @@ name: 'BINARIUM'
 description: 'Zero-configuration library and CLI for building node executables for all platforms and architectures'
 author: 'pigeonposse'
 inputs:
+  build:
+    required: false
+    default: 'node'
+    description: 'Specify the runtime environment. Acceptable values are: node, deno, bun.'
   config:
     required: false
     description: 'Path for config file.'
+    default: './binarium.config.json'
 
 runs:
   using: "composite"
@@ -18,12 +23,19 @@ runs:
       with:
         node-version: 20
         cache: 'pnpm'
+    - name: ⚠️ Validate build input
+      run: |
+        if [[ "${{ inputs.build }}" != "node" && "${{ inputs.build }}" != "deno" && "${{ inputs.build }}" != "bun" ]]; then
+          echo "Error: Invalid input for 'build'. Acceptable values are: node, deno, bun."
+          exit 1
+        fi
+      shell: bash
     - name: ⬇️📦 Install dependencies
       run: pnpm i -g binarium
       shell: bash
 
     - name: 🧩📦 Execute bepp
-      run: binarium --config '${{ inputs.config }}'
+      run: binarium ${inputs.build} --config '${{ inputs.config }}'
       shell: bash
 
 branding:
